name: Deploy Ionic PWA to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract repository name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Find Ionic project directory
        id: find-ionic
        run: |
          APP_PATH=$(find . -type f -name ionic.config.json -exec dirname {} \; | head -n 1)
          if [ -z "$APP_PATH" ]; then
            APP_PATH="."
          fi
          echo "APP_PATH=$APP_PATH" >> $GITHUB_ENV

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd $APP_PATH
          npm ci

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # Check if PWA is already configured by looking for "serviceWorker": true
      - name: Check if PWA is already configured
        run: |
          cd $APP_PATH
          if grep -q '"serviceWorker": true' angular.json; then
            echo "PWA_ALREADY_CONFIGURED=true" >> $GITHUB_ENV
          else
            echo "PWA_ALREADY_CONFIGURED=false" >> $GITHUB_ENV
          fi

      # Check if the app is using standalone components by searching for 'bootstrapApplication'
      - name: Check if app is standalone
        run: |
          cd $APP_PATH
          if grep -q 'bootstrapApplication' src/main.ts; then
            echo "IS_STANDALONE=true" >> $GITHUB_ENV
          else
            echo "IS_STANDALONE=false" >> $GITHUB_ENV
          fi

      # If not PWA configured, run ng add @angular/pwa
      - name: Add PWA support if not configured and needed
        if: env.PWA_ALREADY_CONFIGURED == 'false'
        run: |
          cd $APP_PATH
          # Run ng add for PWA non-interactively
          npx ng add @angular/pwa@latest --project app --force --skip-confirmation || true
          # We use '|| true' to prevent the step from failing if ng add tries to modify files already partially configured.

      # If standalone, ensure provideServiceWorker is present and serviceWorker is enabled in angular.json
      - name: Adjust standalone configuration if needed
        if: env.IS_STANDALONE == 'true'
        run: |
          cd $APP_PATH
          # Ensure serviceWorker: true in angular.json under production configuration
          if ! grep -q '"serviceWorker": true' angular.json; then
            # Insert serviceWorker: true before the ending of the production configuration block
            sed -i 's|"outputHashing": "all"|&,\n          "serviceWorker": true|' angular.json
          fi

          # Check if provideServiceWorker is included in main.ts
          # If not, add it. This assumes a certain structure in main.ts where bootstrapApplication is called.
          if ! grep -q 'provideServiceWorker(' src/main.ts; then
            # Add the import if not present
            if ! grep -q 'from .*@angular/service-worker' src/main.ts; then
              sed -i '1i import { provideServiceWorker } from "@angular/service-worker";' src/main.ts
            fi

            # Add provideServiceWorker to the providers array in bootstrapApplication
            # This example assumes your bootstrapApplication call looks something like:
            # bootstrapApplication(AppComponent, { providers: [ ... ]})
            # We'll insert provideServiceWorker('ngsw-worker.js', { enabled: environment.production }) into providers.
            sed -i '/bootstrapApplication(.*{ providers: \[/ s/\[/\[provideServiceWorker('\''ngsw-worker.js'\'', { enabled: environment.production }), /' src/main.ts
          fi

      - name: Build the Ionic PWA
        run: |
          cd $APP_PATH
          # Use a production configuration so service worker files are generated
          ionic build -- --configuration production --base-href /${{ env.REPO_NAME }}/

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          enablement: pages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '${{ env.APP_PATH }}/www'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
